### ISSUE TITLE
Make active deployments buttons properly responsive

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/democraciaenred.github.io#1]
![23634395-c6a3-4514-bacc-80d696e08ddd](https://cloud.githubusercontent.com/assets/2538465/3164996/a22a0eb4-eb4f-11e3-8c13-aba5b549bc13.png)

**Comment by piamancini** [comment]
This was fixed in ec9cdfb2dfc49d58c599915f2a7b8dc4f86a52f5
